site_name: Simple TOML Configurator Docs
site_description: ""

repo_url: https://github.com/GilbN/Simple-TOML-Configurator
repo_name: GilbN/Simple-TOML-Configurator
edit_uri: https://github.com/GilbN/Simple-TOML-Configurator/edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.indexes
    - navigation.expand
    - navigation.footer
  icon:
    logo: material/book-open-page-variant
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: teal
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: fontawesome/brands/github
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
- mkdocstrings:
- search
- autorefs
- awesome-pages
- section-index
- macros
- include-markdown
- git-revision-date-localized:
    fallback_to_build_date: true
- minify:
    minify_html: true
- mike:

watch:
  - src/
  - changelog.md
  - examples/

extra_css:
  - css/code_select.css

nav:
  - Home: index.md
  - Docs:
    - Configurator: configurator.md
    - Exceptions: exceptions.md
  - Examples:
      - Flask Simple: flask-simple-example.md
      - Flask Custom: flask-custom-example.md
  - How-To Guides:
      - Installation: installation.md
      - Usage: usage-examples.md
  - Changelog: changelog.md

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
      anchor_linenums: true
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.keys
  - toc:
      permalink: true

extra:
  version:
    provider: mike
  homepage: https://github.com/GilbN/Simple-TOML-Configurator
  social:
    - icon: fontawesome/solid/heart
      link: "https://github.com/sponsors/GilbN"
      name: Donate
    - icon: fontawesome/brands/discord
      link: "https://docs.theme-park.dev/discord"
      name: Discord
    - icon: fontawesome/brands/github
      link: "https://github.com/gilbn"
      name: GitHub
